coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "RentalApp/**"
  - "RentalApp.Migrations/**"
  - "RentalApp.Test/**"
  - "RentalApp.Database/Migrations/**"
  - "RentalApp.Database/Models/UserRole.cs"
  - "RentalApp.Database/Models/Role.cs"
  - "RentalApp.Database/Models/RoleConstants.cs"
  - "**/*.g.cs"
  - "**/*.Designer.cs"
