coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "RentalApp/**"
  - "RentalApp.Migrations/**"
  - "RentalApp.Test/**"
  - "RentalApp.Database/Migrations/**"
  - "RentalApp.Database/Models/**"
  - "**/*.g.cs"
  - "**/*.Designer.cs"
