name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Database
      run: dotnet restore RentalApp.Database/RentalApp.Database.csproj

    - name: Build Database
      run: dotnet build RentalApp.Database/RentalApp.Database.csproj --no-restore -c Debug

    - name: Restore Migrations
      run: dotnet restore RentalApp.Migrations/RentalApp.Migrations.csproj

    - name: Build Migrations
      run: dotnet build RentalApp.Migrations/RentalApp.Migrations.csproj --no-restore -c Debug

      - name: Restore Test project
  run: dotnet restore RentalApp.Test/RentalApp.Test.csproj

- name: Build Test project
  run: dotnet build RentalApp.Test/RentalApp.Test.csproj --no-restore -c Debug

- name: Run Tests
  run: dotnet test RentalApp.Test/RentalApp.Test.csproj --no-build -c Debug --settings RentalApp.Test/coverage.runsettings